pipeline {

    agent any

    tools {
        jdk 'JDK21'
        maven 'Maven-3.9'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/ssibelcebeci/testng-project-ci.git'
            }
        }

        stage('Run Test') {
            steps {
                sh 'mvn clean test'
            }
        }

        stage('Generate Allure Report') {
            steps {
                echo "Allure report will be generated by Jenkins post-build action."
            }
        }
    }
}
